version: "3.9"
services:
  app:
    build: .
    ports:
      - '5050:5050'
    depends_on:
      - redis
      - postgres
    env_file:
      - '.env'
  redis:
    image: redis:5-buster
    restart: on-failure
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
  postgres:
    image: postgres:9.4
    env_file:
      - '.env'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volumes/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: on-failure
